server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # Health check endpoint returning HTTP 200 OK
    location = /health {
        default_type application/json;
        return 200 '{"status":"UP","container":"docker","runtime":"containerd","port":80}\n';
    }

    # Error handling
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
